type: object
description: |
  Response containing all ETIM classifications for a single product.
  Returns the product identification keys and all associated ETIM classifications.
additionalProperties: false
required:
  - data
properties:
  data:
    $ref: ./ProductEtimClassificationsResponseData.yaml
examples:
  - data:
      manufacturerIdGln: "1234567890123"
      manufacturerProductNumber: "929002376910"
      etimClassifications:
        - etimClassCode: "EC002745"
          etimClassVersion: 1
          etimReleaseVersion: "9.0"
          etimFeatures:
            - etimFeatureCode: "EF000123"
              etimValueCode: "EV000789"
            - etimFeatureCode: "EF000456"
              etimValueNumeric: 230.0
        - etimClassCode: "EC001234"
          etimClassVersion: 2
          etimReleaseVersion: "11.0"
          etimFeatures:
            - etimFeatureCode: "EF000789"
              etimValueLogical: true
