type: object
description: |
  Response containing product details for a single product.
  Uses the same `ProductDetailsSummary` model as the bulk endpoint `/bulk/product-details`.
  
  Note: Product descriptions are available through the dedicated `/descriptions` subresource
  which supports language filtering.
additionalProperties: false
required:
  - data
properties:
  data:
    $ref: ../domain/ProductDetailsSummary.yaml
    description: |
      Product details including status, type, warranties, and product groups.
examples:
  - data:
      manufacturerIdGln: "1234567890123"
      manufacturerProductNumber: "929002376910"
      productStatus: "ACTIVE"
      productType: "PHYSICAL"
      customisableProduct: false
      hasSerialNumber: true
      warrantyConsumer: 24
      warrantyBusiness: 36
      relatedManufacturerProductGroup:
        - "Smart Lighting"
        - "LED Bulbs"
