type: object
description: |
  Response containing a single product with all its components.
  
  The product key (`manufacturerIdGln` + `manufacturerProductNumber`) is at the root level,
  with nested objects for each component:
  - `identification`: Manufacturer details, GTINs, brand, dates, customs data
  - `details`: Status, type, warranties, product groups
  - `descriptions`: Array of multilingual descriptions (nested, not flattened)
  - `etimClassifications`: Array of ETIM classifications with embedded features (nested)
  
  This structure aligns with the subresource endpoints (`/identification`, `/details`, 
  `/descriptions`, `/etim-classifications`) which all include the key at the root level.
additionalProperties: false
required:
  - data
properties:
  data:
    type: object
    additionalProperties: false
    required:
      - manufacturerIdGln
      - manufacturerProductNumber
      - identification
    properties:
      manufacturerIdGln:
        type: string
        pattern: "^[0-9]{13}$"
        description: Global Location Number (GLN) uniquely identifying the manufacturer
        examples:
          - "1234567890123"
      manufacturerProductNumber:
        type: string
        minLength: 1
        maxLength: 35
        description: Manufacturer's unique product number/code
        examples:
          - "929002376910"
      identification:
        $ref: ../domain/ProductIdentification.yaml
        description: |
          Product identification information including manufacturer details, GTINs, brand, 
          dates, and customs data.
      details:
        $ref: ../domain/ProductDetails.yaml
        description: |
          Product details including status, type, warranties, and product groups.
      descriptions:
        type: ["array", "null"]
        description: |
          Array of multilingual product descriptions. Each item contains descriptions
          in a specific language. Returns null if no descriptions are available.
        items:
          $ref: ../domain/ProductDescription.yaml
      etimClassifications:
        type: ["array", "null"]
        description: |
          Array of ETIM classifications for this product with embedded features.
          Returns null if the product has no ETIM classifications.
          Multiple classifications can exist across different ETIM releases.
        items:
          $ref: ../domain/EtimClassification.yaml
examples:
  - data:
      manufacturerIdGln: "1234567890123"
      manufacturerProductNumber: "929002376910"
      identification:
        manufacturerName: "Philips Lighting B.V."
        manufacturerShortname: "Philips"
        productGtins:
          - "8718699673826"
        brandName: "Hue"
        productAnnouncementDate: "2024-01-15"
        productValidityDate: "2024-03-01"
        productObsolescenceDate: null
        customsCommodityCode: "8539502090"
        countryOfOrigin:
          - "NL"
      details:
        productStatus: "ACTIVE"
        productType: "PHYSICAL"
        customisableProduct: false
        hasSerialNumber: true
        warrantyConsumer: 24
        warrantyBusiness: 36
      descriptions:
        - descriptionLanguage: "en-GB"
          minimalProductDescription: "LED Smart Bulb E27"
          uniqueMainProductDescription: "Philips Hue White and Color Ambiance E27 LED Smart Bulb with Bluetooth"
          productKeyword:
            - "smart lighting"
            - "LED"
            - "color"
      etimClassifications:
        - etimClassCode: "EC002745"
          etimClassVersion: 1
          etimReleaseVersion: "9.0"
          etimFeatures:
            - etimFeatureCode: "EF012345"
              etimValueNumeric: 10
