type: object
description: |
  Response containing product identification information for a single product.
  The product key is at the root level, with identification details nested inside.
  
  This structure aligns with other single-product subresource responses
  (`/details`, `/descriptions`, `/etim-classifications`).
additionalProperties: false
required:
  - data
properties:
  data:
    type: object
    additionalProperties: false
    required:
      - manufacturerIdGln
      - manufacturerProductNumber
      - identification
    properties:
      manufacturerIdGln:
        type: string
        pattern: "^[0-9]{13}$"
        description: Global Location Number (GLN) uniquely identifying the manufacturer
        examples:
          - "1234567890123"
      manufacturerProductNumber:
        type: string
        minLength: 1
        maxLength: 35
        description: Manufacturer's unique product number/code
        examples:
          - "929002376910"
      identification:
        $ref: ../domain/ProductIdentification.yaml
        description: |
          Product identification information including manufacturer details, GTINs, brand,
          dates, and customs data.
examples:
  - data:
      manufacturerIdGln: "1234567890123"
      manufacturerProductNumber: "929002376910"
      identification:
        manufacturerName: "Philips Lighting B.V."
        manufacturerShortname: "Philips"
        productGtins:
          - "8718699673826"
        brandName: "Hue"
        productAnnouncementDate: "2024-01-15"
        productValidityDate: "2024-03-01"
        productObsolescenceDate: null
        customsCommodityCode: "8539502090"
        countryOfOrigin:
          - "NL"
