get:
  operationId: getBulkProductDescriptions
  tags:
    - Products bulk
  summary: Retrieve product descriptions in bulk
  description: |
    Retrieve product descriptions in bulk with cursor-based pagination.
    Returns a flattened structure where each row represents a single language description
    with the product identifier (manufacturerIdGln + manufacturerProductNumber).
    
    This flattened structure is optimized for:
    - Predictable payload sizes per row
    - Efficient cursor-based pagination
    - ETL/data warehouse ingestion
    - Streaming data processing
    - Language filtering at row level
    
    ## Language Filtering
    
    Use the `language` parameter to filter descriptions to specific language(s):
    - `?language=en-GB` - Returns only English (GB) descriptions
    - `?language=en-GB&language=de-DE` - Returns English and German descriptions
    - Omit parameter to return all available languages
    
    ## Response Structure
    
    Each row in the response contains:
    - `manufacturerIdGln` - Manufacturer GLN identifier (part of product key)
    - `manufacturerProductNumber` - Product number (part of product key)
    - `descriptionLanguage` - Language code for this description
    - `minimalProductDescription` - Short description (required)
    - `uniqueMainProductDescription` - Unique main description
    - `fullProductDescription` - Full detailed description
    - `productMarketingText` - Marketing content
    - `productSpecificationText` - Technical specifications
    - `productApplicationInstructions` - Usage instructions
    - `productKeyword` - Search keywords array
    - `productPageUrl` - Product page URL
    
    A product with descriptions in 3 languages will result in 3 rows.
  parameters:
    - $ref: ../../../../shared/parameters/query/cursor.yaml
    - $ref: ../../../../shared/parameters/query/limit.yaml
    - $ref: ../../../../shared/parameters/query/selection-id.yaml
    - $ref: ../../../../shared/parameters/query/manufacturer-id-gln.yaml
    - $ref: ../../../../shared/parameters/query/mutation-date.yaml
    - $ref: ../../../../shared/parameters/query/language.yaml
  responses:
    '200':
      description: Successfully retrieved product descriptions
      content:
        application/json:
          schema:
            $ref: ../../schemas/responses/BulkProductDescriptionsResponse.yaml
    '400':
      $ref: ../../../../shared/responses/400-bad-request.yaml
    '401':
      $ref: ../../../../shared/responses/401-unauthorized.yaml
    '403':
      $ref: ../../../../shared/responses/403-forbidden.yaml
    '500':
      $ref: ../../../../shared/responses/500-internal-server-error.yaml
