get:
  operationId: getBulkProductIdentifications
  tags:
    - Products bulk
  summary: Retrieve product identification information in bulk
  description: |
    Retrieve product identification information in bulk with cursor-based pagination.
    Returns only identification-related fields: manufacturer details, product numbers,
    GTINs, brand information, lifecycle dates, customs codes, and country of origin.
    
    Use this endpoint for lightweight product identification synchronization.
  parameters:
    - $ref: ../../../../shared/parameters/query/cursor.yaml
    - $ref: ../../../../shared/parameters/query/limit.yaml
    - $ref: ../../../../shared/parameters/query/selection-id.yaml
    - $ref: ../../../../shared/parameters/query/manufacturer-id-gln.yaml
    - $ref: ../../../../shared/parameters/query/mutation-date-time.yaml
  responses:
    '200':
      description: Successfully retrieved product identifications
      content:
        application/json:
          schema:
            $ref: ../../schemas/responses/BulkProductIdentificationsResponse.yaml
    '400':
      $ref: ../../../../shared/responses/400-bad-request.yaml
    '401':
      $ref: ../../../../shared/responses/401-unauthorized.yaml
    '403':
      $ref: ../../../../shared/responses/403-forbidden.yaml
    '500':
      $ref: ../../../../shared/responses/500-internal-server-error.yaml
