get:
  operationId: getBulkProductEtimClassifications
  tags:
    - Products bulk
  summary: Retrieve product ETIM classifications in bulk
  description: |
    Retrieve product ETIM classification information in bulk with cursor-based pagination.
    Returns ETIM class codes, features, and version information.
    
    **ETIM Release Filtering**: Use the optional `etimReleaseVersion` query parameter
    to filter classifications to a specific ETIM release version (e.g., "9.0", "10.0").
    
    Use this endpoint for ETIM classification synchronization.
  parameters:
    - $ref: ../../../../shared/parameters/query/cursor.yaml
    - $ref: ../../../../shared/parameters/query/limit.yaml
    - $ref: ../../../../shared/parameters/query/selection-id.yaml
    - $ref: ../../../../shared/parameters/query/manufacturer-id-gln.yaml
    - $ref: ../../../../shared/parameters/query/mutation-date-time.yaml
    - $ref: ../../../../shared/parameters/query/etim-release-version.yaml
  responses:
    '200':
      description: Successfully retrieved product ETIM classifications
      content:
        application/json:
          schema:
            $ref: ../../schemas/responses/BulkProductEtimClassificationsResponse.yaml
    '400':
      $ref: ../../../../shared/responses/400-bad-request.yaml
    '401':
      $ref: ../../../../shared/responses/401-unauthorized.yaml
    '403':
      $ref: ../../../../shared/responses/403-forbidden.yaml
    '500':
      $ref: ../../../../shared/responses/500-internal-server-error.yaml
