get:
  operationId: getBulkProductLcaDeclarations
  tags:
    - Products bulk
  summary: Retrieve product LCA declarations in bulk
  description: |
    Retrieve product LCA (Life Cycle Assessment) declaration data in a flattened format 
    with cursor-based pagination.
    
    **Flattened Structure**: Each row represents a single life cycle stage declaration within 
    a product's LCA environmental data. This structure is optimized for:
    - Predictable payload sizes (each row has consistent structure)
    - Efficient cursor-based pagination by declaration
    - ETL/data warehouse ingestion
    - Streaming data processing
    - Filtering by life cycle stage
    
    **Payload Optimization**: Optional properties with null values are omitted from the response
    to minimize payload size. Clients should treat missing properties as null/not applicable.
    
    **Parent Context**: Each row includes key parent fields from LcaEnvironmental
    (`declaredUnitUnit`, `declaredUnitQuantity`, `lcaReferenceLifetime`, `thirdPartyVerification`)
    to provide necessary context for interpreting the environmental indicators.
    
    **Data Reconstruction**: To reconstruct the hierarchical structure:
    1. Group rows by `manufacturerIdGln` + `manufacturerProductNumber` for products
    2. All rows for a product share the same parent context (declared unit, lifetime, verification)
    3. Each row represents a different life cycle stage (A1-A3, B1-B7, C1-C4, D)
    
    **Life Cycle Stage Filtering**: Use the optional `lifeCycleStage` query parameter
    to filter declarations to a specific EN 15804 life cycle stage.
    
    **Use case**: Ideal for bulk synchronization of environmental product declaration data 
    to external systems, sustainability reporting, or analytics platforms.
  parameters:
    - $ref: ../../../../shared/parameters/query/cursor.yaml
    - $ref: ../../../../shared/parameters/query/limit.yaml
    - $ref: ../../../../shared/parameters/query/selection-id.yaml
    - $ref: ../../../../shared/parameters/query/manufacturer-id-gln-filter.yaml
    - $ref: ../../../../shared/parameters/query/mutation-date-time.yaml
    - $ref: ../../../../shared/parameters/query/life-cycle-stage.yaml
  responses:
    '200':
      description: Successfully retrieved product LCA declarations
      content:
        application/json:
          schema:
            $ref: ../../schemas/responses/BulkProductLcaDeclarationsResponse.yaml
          examples:
            multipleProducts:
              summary: Multiple products with various life cycle stages
              value:
                data:
                  # Product 1, Production stage (A1-A3)
                  - manufacturerIdGln: "1234567890123"
                    manufacturerProductNumber: "929002376910"
                    declaredUnitUnit: "PCE"
                    declaredUnitQuantity: 1
                    lcaReferenceLifetime: 25
                    thirdPartyVerification: "EXT"
                    lifeCycleStage: "A1-A3"
                    lcaDeclarationIndicator: "MDE"
                    declaredUnitGwpTotal: 15.75
                    declaredUnitGwpFossil: 14.25
                    declaredUnitGwpBiogenic: 1.2
                    declaredUnitAp: 0.05
                    declaredUnitAdpf: 185.5
                  # Product 1, End-of-life stage (C1-C4)
                  - manufacturerIdGln: "1234567890123"
                    manufacturerProductNumber: "929002376910"
                    declaredUnitUnit: "PCE"
                    declaredUnitQuantity: 1
                    lcaReferenceLifetime: 25
                    thirdPartyVerification: "EXT"
                    lifeCycleStage: "C1-C4"
                    lcaDeclarationIndicator: "AGG"
                    declaredUnitGwpTotal: 2.5
                    declaredUnitAdpf: 35.0
                  # Product 1, Module D (benefits)
                  - manufacturerIdGln: "1234567890123"
                    manufacturerProductNumber: "929002376910"
                    declaredUnitUnit: "PCE"
                    declaredUnitQuantity: 1
                    lcaReferenceLifetime: 25
                    thirdPartyVerification: "EXT"
                    lifeCycleStage: "D"
                    lcaDeclarationIndicator: "MDE"
                    declaredUnitGwpTotal: -5.2
                    declaredUnitAdpf: -45.0
                  # Product 2, Production stage
                  - manufacturerIdGln: "9876543210987"
                    manufacturerProductNumber: "CABLE-CU-100M"
                    declaredUnitUnit: "KGM"
                    declaredUnitQuantity: 1
                    lcaReferenceLifetime: 50
                    thirdPartyVerification: "INT"
                    lifeCycleStage: "A1-A3"
                    lcaDeclarationIndicator: "MND"
                    declaredUnitGwpTotal: 8.5
                    declaredUnitAdpe: 0.0015
                    declaredUnitAdpf: 120.0
                meta:
                  cursor: "eyJtYW51ZmFjdHVyZXJJZEdsbkgiOiI5ODc2NTQzMjEwOTg3IiwibWFudWZhY3R1cmVyUHJvZHVjdE51bWJlciI6IkNBQkxFLUNVLTEwME0iLCJsaWZlQ3ljbGVTdGFnZSI6IkExLUEzIn0="
                  hasNext: true
                  hasPrev: false
                  limit: 1000
                  estimatedTotal: 12540
            filteredByStage:
              summary: Filtered to production stage only
              value:
                data:
                  - manufacturerIdGln: "1234567890123"
                    manufacturerProductNumber: "929002376910"
                    declaredUnitUnit: "PCE"
                    declaredUnitQuantity: 1
                    lcaReferenceLifetime: 25
                    thirdPartyVerification: "EXT"
                    lifeCycleStage: "A1-A3"
                    lcaDeclarationIndicator: "MDE"
                    declaredUnitGwpTotal: 15.75
                    declaredUnitGwpFossil: 14.25
                    declaredUnitAdpf: 185.5
                meta:
                  cursor: null
                  hasNext: false
                  hasPrev: false
                  limit: 1000
                  estimatedTotal: 4180
            emptyResult:
              summary: No LCA declarations found
              value:
                data: []
                meta:
                  cursor: null
                  hasNext: false
                  hasPrev: false
                  limit: 1000
                  estimatedTotal: 0
    '400':
      $ref: ../../../../shared/responses/400-bad-request.yaml
    '401':
      $ref: ../../../../shared/responses/401-unauthorized.yaml
    '403':
      $ref: ../../../../shared/responses/403-forbidden.yaml
    '500':
      $ref: ../../../../shared/responses/500-internal-server-error.yaml
