get:
  operationId: getProductIdentification
  tags:
    - Products single
  summary: Retrieve product identification
  description: |
    Retrieve identification information for a specific manufacturer product combination.
    
    This endpoint returns product identification data including manufacturer details,
    GTINs, brand information, lifecycle dates, and customs data for a single product
    identified by the composite key of `manufacturerIdGln` and `manufacturerProductNumber`.
    
    The product key is at the root level, with identification details nested inside.
    This structure aligns with other single-product subresource responses.
    
    **No pagination** - Returns exactly one product's identification or 404 if not found.
  parameters:
    - $ref: ../../../shared/parameters/path/manufacturer-id-gln.yaml
    - $ref: ../../../shared/parameters/path/manufacturer-product-number.yaml
  responses:
    '200':
      description: Successfully retrieved product identification
      content:
        application/json:
          schema:
            $ref: ../schemas/responses/ProductIdentificationResponse.yaml
          examples:
            fullIdentification:
              summary: Complete product identification
              value:
                data:
                  manufacturerIdGln: "1234567890123"
                  manufacturerProductNumber: "929002376910"
                  identification:
                    manufacturerName: "Philips Lighting B.V."
                    manufacturerShortname: "Philips"
                    productGtins:
                      - "8718699673826"
                    brandName: "Hue"
                    productAnnouncementDate: "2024-01-15"
                    productValidityDate: "2024-03-01"
                    productObsolescenceDate: null
                    customsCommodityCode: "8539502090"
                    countryOfOrigin:
                      - "NL"
            minimalIdentification:
              summary: Minimal product identification
              value:
                data:
                  manufacturerIdGln: "1234567890123"
                  manufacturerProductNumber: "LED-12345-A"
                  identification:
                    manufacturerName: "OSRAM GmbH"
    '400':
      $ref: ../../../shared/responses/400-bad-request.yaml
    '401':
      $ref: ../../../shared/responses/401-unauthorized.yaml
    '403':
      $ref: ../../../shared/responses/403-forbidden.yaml
    '404':
      description: Product not found
      content:
        application/json:
          schema:
            $ref: ../../../shared/schemas/common/ProblemDetails.yaml
          example:
            type: "https://api.product.2ba.nl/problems/not-found"
            title: "Product Not Found"
            status: 404
            detail: "No product found with manufacturer GLN '1234567890123' and product number '929002376910'"
            instance: "https://api.product.2ba.nl/v1/products/1234567890123/929002376910/identification"
    '500':
      $ref: ../../../shared/responses/500-internal-server-error.yaml
