type: object
description: |
  Product ETIM classification information for bulk retrieval.
  Contains ETIM class codes, versions, and feature data.
additionalProperties: false
required:
  - manufacturerIdGln
  - manufacturerProductNumber
properties:
  manufacturerIdGln:
    type: string
    pattern: "^[0-9]{13}$"
  manufacturerProductNumber:
    type: string
    minLength: 1
    maxLength: 35
  etimClassifications:
    type: ["array", "null"]
    items:
      $ref: ./EtimClassification.yaml

examples:
  - manufacturerIdGln: "1234567890123"
    manufacturerProductNumber: "929002376910"
    etimClassifications:
      - etimClassCode: "EC002745"
        etimClassVersion: 1
        etimReleaseVersions:
          - "9.0"
          - "10.0"
        etimFeatures:
          - etimFeatureCode: "EF000123"
            etimValueCode: "EV000789"
