type: object
description: |
  Product details information for bulk retrieval.
  Contains descriptions, status, warranties, and product groups.
additionalProperties: false
required:
  - manufacturerIdGln
  - manufacturerProductNumber
  - productDescriptions
properties:
  manufacturerIdGln:
    type: string
    pattern: "^[0-9]{13}$"
  manufacturerProductNumber:
    type: string
    minLength: 1
    maxLength: 35
  productStatus:
    $ref: ../enums/ProductStatus.yaml
  productType:
    $ref: ../enums/ProductType.yaml
  customisableProduct:
    type: ["boolean", "null"]
  hasSerialNumber:
    type: ["boolean", "null"]
  warrantyConsumer:
    type: ["integer", "null"]
    minimum: 0
    exclusiveMaximum: 1000
  warrantyBusiness:
    type: ["integer", "null"]
    minimum: 0
    exclusiveMaximum: 1000
  relatedManufacturerProductGroup:
    type: ["array", "null"]
    uniqueItems: true
    items:
      type: string
      minLength: 1
      maxLength: 50
  productDescriptions:
    type: array
    minItems: 1
    items:
      $ref: ./ProductDescription.yaml

examples:
  - manufacturerIdGln: "1234567890123"
    manufacturerProductNumber: "929002376910"
    productStatus: "ACTIVE"
    productType: "PHYSICAL"
    warrantyConsumer: 24
    productDescriptions:
      - descriptionLanguage: "en-GB"
        minimalProductDescription: "LED Smart Bulb E27"
        uniqueMainProductDescription: "Philips Hue White and Color Ambiance E27 LED Smart Bulb"
