type: object
description: |
  Flattened product LCA declaration for bulk retrieval.
  Each row represents a single life cycle declaration within a product's LCA environmental data.
  
  This flattened structure is optimized for:
  - Predictable payload sizes per row
  - Efficient cursor-based pagination
  - ETL/data warehouse ingestion
  - Streaming data processing
  
  **Payload Optimization**: Optional properties with null values are omitted from the response
  to minimize payload size. Clients should treat missing properties as null/not applicable.
  
  **Parent context fields**: Key fields from the parent LcaEnvironmental object are included
  (`declaredUnitUnit`, `declaredUnitQuantity`, `lcaReferenceLifetime`, `thirdPartyVerification`)
  to provide necessary context for interpreting the environmental indicators.
additionalProperties: false
required:
  - productRef
  - lifeCycleStage
  - lcaDeclarationIndicator
  - declaredUnitUnit
  - declaredUnitQuantity
  - lcaReferenceLifetime
  - thirdPartyVerification
properties:
  # Product reference
  productRef:
    description: |
      Server-generated opaque reference key that identifies the parent product.
      Use this to correlate with the corresponding product record from the
      `/bulk/product-details` endpoint.
      
      This is a technical identifier not present in the ETIM xChange domain model.
    $ref: ../../../../shared/schemas/identifiers/TechnicalId.yaml
    examples:
      - "prod-929002376910"
      - "f47ac10b-58cc-4372-a567-0e02b2c3d479"
  
  # Parent LcaEnvironmental context fields
  declaredUnitUnit:
    type: string
    enum:
      - "KGM"
      - "LTR"
      - "MTK"
      - "MTQ"
      - "MTR"
      - "PCE"
      - "TNE"
      - "FOT"
      - "FTK"
      - "FTQ"
      - "LBR"
      - "LTN"
      - "YDK"
      - "YRD"
    description: |
      Unit of measurement for the declared/functional unit in LCA.
      
      Metric units:
      - `KGM`: Kilogram
      - `LTR`: Liter
      - `MTK`: Square meter
      - `MTQ`: Cubic meter
      - `MTR`: Meter
      - `PCE`: Piece/unit
      - `TNE`: Tonne
      
      Imperial units:
      - `FOT`: Foot
      - `FTK`: Square foot
      - `FTQ`: Cubic foot
      - `LBR`: Pound
      - `LTN`: Long ton
      - `YDK`: Square yard
      - `YRD`: Yard
      
      **ETIM xChange**: `DeclaredUnitUnit`
      **Path**: `Supplier[].Product[].LcaEnvironmental.DeclaredUnitUnit`
    examples:
      - "KGM"
      - "PCE"
      - "MTK"
  
  declaredUnitQuantity:
    type: number
    format: decimal
    minimum: 0
    multipleOf: 0.0001
    maximum: 99999999999.9999
    description: |
      Quantity of the declared/functional unit for LCA calculations.
      Converted from ETIM xChange string pattern to number type.
      
      **ETIM xChange**: `DeclaredUnitQuantity` (string with pattern)
      **Path**: `Supplier[].Product[].LcaEnvironmental.DeclaredUnitQuantity`
    examples:
      - 1
      - 10.5
      - 100
  
  lcaReferenceLifetime:
    type: integer
    minimum: 0
    description: |
      Reference service life/lifetime for LCA calculations in years.
      
      **ETIM xChange**: `LcaReferenceLifetime`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaReferenceLifetime`
    examples:
      - 25
      - 10
      - 50
  
  thirdPartyVerification:
    type: string
    enum:
      - "none"
      - "internally"
      - "externally"
    description: |
      Type of third-party verification for LCA/EPD data.
      
      - `none`: No third-party verification
      - `internally`: Internal verification
      - `externally`: External independent verification
      
      **ETIM xChange**: `ThirdPartyVerification`
      **Path**: `Supplier[].Product[].LcaEnvironmental.ThirdPartyVerification`
    examples:
      - "externally"
      - "none"
  
  # LcaDeclaration fields (flattened)
  lifeCycleStage:
    type: string
    enum:
      - "A1"
      - "A2"
      - "A3"
      - "A1-A3"
      - "A4"
      - "A5"
      - "B1"
      - "B2"
      - "B3"
      - "B4"
      - "B5"
      - "B6"
      - "B7"
      - "B1-B7"
      - "C1"
      - "C2"
      - "C3"
      - "C4"
      - "C1-C4"
      - "D"
    description: |
      Life cycle assessment stage according to EN 15804.
      
      Product stage (A):
      - `A1`: Raw material supply
      - `A2`: Transport to manufacturer
      - `A3`: Manufacturing
      - `A1-A3`: Combined product stage
      - `A4`: Transport to building site
      - `A5`: Installation into building
      
      Use stage (B):
      - `B1`: Use/Application
      - `B2`: Maintenance
      - `B3`: Repair
      - `B4`: Replacement
      - `B5`: Refurbishment
      - `B6`: Operational energy use
      - `B7`: Operational water use
      - `B1-B7`: Combined use stage
      
      End of life stage (C):
      - `C1`: Deconstruction/demolition
      - `C2`: Transport to waste processing
      - `C3`: Waste processing
      - `C4`: Disposal
      - `C1-C4`: Combined end of life stage
      
      Beyond life cycle (D):
      - `D`: Reuse, recovery, recycling potential
      
      **ETIM xChange**: `LifeCycleStage`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].LifeCycleStage`
    examples:
      - "A1-A3"
      - "B6"
      - "C1-C4"
  
  lcaDeclarationIndicator:
    type: string
    enum:
      - "MDE"
      - "MND"
      - "MNR"
      - "AGG"
    description: |
      Type of LCA declaration data.
      
      - `MDE`: Manufacturer-specific data with external verification
      - `MND`: Manufacturer-specific data without external verification
      - `MNR`: Manufacturer-specific data not representative
      - `AGG`: Industry average/aggregated data
      
      **ETIM xChange**: `LcaDeclarationIndicator`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].LcaDeclarationIndicator`
    examples:
      - "MDE"
      - "AGG"
  
  # Environmental indicators
  declaredUnitGwpTotal:
    type: ["number", "null"]
    description: |
      Total Global Warming Potential (GWP) in kg CO2 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitGwpTotal`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitGwpTotal`
    examples:
      - 15.75
      - 0.85
  
  declaredUnitGwpFossil:
    type: ["number", "null"]
    description: |
      Fossil Global Warming Potential in kg CO2 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitGwpFossil`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitGwpFossil`
    examples:
      - 14.25
  
  declaredUnitGwpBiogenic:
    type: ["number", "null"]
    description: |
      Biogenic Global Warming Potential in kg CO2 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitGwpBiogenic`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitGwpBiogenic`
    examples:
      - 1.2
  
  declaredUnitGwpLuluc:
    type: ["number", "null"]
    description: |
      Global Warming Potential from Land Use and Land Use Change (GWP-LULUC) 
      in kg CO2 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitGwpLuluc`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitGwpLuluc`
    examples:
      - 0.25
  
  declaredUnitAp:
    type: ["number", "null"]
    description: |
      Acidification Potential (AP) in kg SO2 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitAp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitAp`
    examples:
      - 0.05
  
  declaredUnitEpFreshwater:
    type: ["number", "null"]
    description: |
      Eutrophication Potential for freshwater in kg PO4 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitEpFreshwater`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitEpFreshwater`
    examples:
      - 0.002
  
  declaredUnitEpMarine:
    type: ["number", "null"]
    description: |
      Eutrophication Potential for marine water (EP-marine) in kg N equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitEpMarine`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitEpMarine`
    examples:
      - 0.0015
  
  declaredUnitEpTerrestrial:
    type: ["number", "null"]
    description: |
      Eutrophication Potential for terrestrial ecosystems (EP-terrestrial) 
      in mol N equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitEpTerrestrial`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitEpTerrestrial`
    examples:
      - 0.12
  
  declaredUnitPocp:
    type: ["number", "null"]
    description: |
      Photochemical Ozone Creation Potential (POCP) in kg NMVOC equivalent per declared unit.
      Also known as summer smog potential.
      
      **ETIM xChange**: `DeclaredUnitPocp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitPocp`
    examples:
      - 0.035
  
  declaredUnitOdp:
    type: ["number", "null"]
    description: |
      Ozone Depletion Potential (ODP) in kg CFC-11 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitOdp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitOdp`
    examples:
      - 0.0000012
  
  declaredUnitAdpe:
    type: ["number", "null"]
    description: |
      Abiotic Depletion Potential for non-fossil resources (ADP-elements) 
      in kg Sb equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitAdpe`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitAdpe`
    examples:
      - 0.00025
  
  declaredUnitAdpf:
    type: ["number", "null"]
    description: |
      Abiotic Depletion Potential for fossil resources (ADP-fossil) in MJ per declared unit.
      
      **ETIM xChange**: `DeclaredUnitAdpf`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitAdpf`
    examples:
      - 185.5
  
  declaredUnitWdp:
    type: ["number", "null"]
    description: |
      Water Deprivation Potential (WDP) in m³ world equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitWdp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitWdp`
    examples:
      - 2.5
  
  declaredUnitPert:
    type: ["number", "null"]
    description: |
      Use of renewable primary energy resources (PERT) in MJ per declared unit.
      Total renewable primary energy.
      
      **ETIM xChange**: `DeclaredUnitPert`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitPert`
    examples:
      - 45.2
  
  declaredUnitPenrt:
    type: ["number", "null"]
    description: |
      Use of non-renewable primary energy resources (PENRT) in MJ per declared unit.
      Total non-renewable primary energy.
      
      **ETIM xChange**: `DeclaredUnitPenrt`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitPenrt`
    examples:
      - 195.8
  
  declaredUnitPm:
    type: ["number", "null"]
    description: |
      Particulate Matter emissions (PM) expressed as disease incidence per declared unit.
      
      **ETIM xChange**: `DeclaredUnitPm`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitPm`
    examples:
      - 0.0000015
  
  declaredUnitIrp:
    type: ["number", "null"]
    description: |
      Ionising Radiation Potential (IRP) in kBq U235 equivalent per declared unit.
      
      **ETIM xChange**: `DeclaredUnitIrp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitIrp`
    examples:
      - 1.25
  
  declaredUnitEtpfw:
    type: ["number", "null"]
    description: |
      Ecotoxicity Potential for freshwater (ETP-fw) in CTUe (Comparative Toxic Unit for ecosystems) 
      per declared unit.
      
      **ETIM xChange**: `DeclaredUnitEtpfw`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitEtpfw`
    examples:
      - 125.5
  
  declaredUnitHtpc:
    type: ["number", "null"]
    description: |
      Human Toxicity Potential - cancer effects (HTP-c) in CTUh (Comparative Toxic Unit for humans) 
      per declared unit.
      
      **ETIM xChange**: `DeclaredUnitHtpc`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitHtpc`
    examples:
      - 0.0000025
  
  declaredUnitHtpnc:
    type: ["number", "null"]
    description: |
      Human Toxicity Potential - non-cancer effects (HTP-nc) in CTUh (Comparative Toxic Unit for humans) 
      per declared unit.
      
      **ETIM xChange**: `DeclaredUnitHtpnc`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitHtpnc`
    examples:
      - 0.000045
  
  declaredUnitSqp:
    type: ["number", "null"]
    description: |
      Soil Quality Potential (SQP) - dimensionless indicator per declared unit.
      Measures the impact on soil quality.
      
      **ETIM xChange**: `DeclaredUnitSqp`
      **Path**: `Supplier[].Product[].LcaEnvironmental.LcaDeclaration[].DeclaredUnitSqp`
    examples:
      - 15.5

examples:
  # Production stage declaration with common indicators
  - productRef: "prod-929002376910"
    declaredUnitUnit: "PCE"
    declaredUnitQuantity: 1
    lcaReferenceLifetime: 25
    thirdPartyVerification: "externally"
    lifeCycleStage: "A1-A3"
    lcaDeclarationIndicator: "MDE"
    declaredUnitGwpTotal: 15.75
    declaredUnitGwpFossil: 14.25
    declaredUnitGwpBiogenic: 1.2
    declaredUnitGwpLuluc: 0.3
    declaredUnitAp: 0.05
    declaredUnitEpFreshwater: 0.002
    declaredUnitPocp: 0.035
    declaredUnitOdp: 0.0000012
    declaredUnitAdpf: 185.5
    declaredUnitPert: 45.2
    declaredUnitPenrt: 195.8
  
  # End-of-life stage declaration
  - productRef: "prod-929002376910"
    declaredUnitUnit: "PCE"
    declaredUnitQuantity: 1
    lcaReferenceLifetime: 25
    thirdPartyVerification: "externally"
    lifeCycleStage: "C1-C4"
    lcaDeclarationIndicator: "AGG"
    declaredUnitGwpTotal: 2.5
    declaredUnitGwpFossil: 2.3
    declaredUnitAdpf: 35.0
  
  # Benefits beyond system boundary (Module D)
  - productRef: "prod-929002376910"
    declaredUnitUnit: "PCE"
    declaredUnitQuantity: 1
    lcaReferenceLifetime: 25
    thirdPartyVerification: "externally"
    lifeCycleStage: "D"
    lcaDeclarationIndicator: "MDE"
    declaredUnitGwpTotal: -5.2
    declaredUnitAdpf: -45.0
  
  # Different product with kg-based declared unit
  - productRef: "prod-cable-cu-100m"
    declaredUnitUnit: "KGM"
    declaredUnitQuantity: 1
    lcaReferenceLifetime: 50
    thirdPartyVerification: "internally"
    lifeCycleStage: "A1-A3"
    lcaDeclarationIndicator: "MND"
    declaredUnitGwpTotal: 8.5
    declaredUnitAdpe: 0.0015
    declaredUnitAdpf: 120.0
