type: object
additionalProperties: false
required:
  - attachmentRef
  - attachmentType
  - attachmentDetails
properties:
  attachmentRef:
    description: |
      Server-generated opaque reference key that uniquely identifies this attachment group
      within the scope of a product.
      
      This is a technical identifier not present in the ETIM xChange domain model.
    $ref: ../../../../shared/schemas/identifiers/TechnicalId.yaml
    examples:
      - "att-image-001"
      - "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
  
  attachmentType:
    $ref: ../enums/AttachmentType.yaml
    description: |
      ETIM standardized type code for the attachment.
      
      **ETIM xChange**: `AttachmentType`  
      **Path**: `Supplier[].Product[].ProductAttachments[].AttachmentType`
  
  attachmentTypeSpecification:
    $ref: ../enums/AttachmentTypeSpecification.yaml
    description: |
      Additional specification code providing more detail about the attachment type.
      
      **ETIM xChange**: `AttachmentTypeSpecification`  
      **Path**: `Supplier[].Product[].ProductAttachments[].AttachmentTypeSpecification`
  
  attachmentOrder:
    type: ["integer", "null"]
    minimum: 1
    description: |
      Display order/sequence number for this attachment when multiple attachments are present.
      Lower numbers indicate higher priority or preferred display order.
      
      **ETIM xChange**: `AttachmentOrder`  
      **Path**: `Supplier[].Product[].ProductAttachments[].AttachmentOrder`
    examples:
      - 1
      - 2
      - null
  
  attachmentDetails:
    type: array
    minItems: 1
    items:
      $ref: ./AttachmentDetails.yaml
    description: |
      Array of attachment file details. Multiple files can be provided for the same attachment type
      (e.g., same datasheet in different languages or formats).
      
      **ETIM xChange**: `AttachmentDetails`  
      **Path**: `Supplier[].Product[].ProductAttachments[].AttachmentDetails[]`

examples:
  - attachmentRef: "att-image-001"
    attachmentType: "ATX001"
    attachmentTypeSpecification: "MDX002"
    attachmentOrder: 1
    attachmentDetails:
      - attachmentUri: "https://images.manufacturer.com/products/LED-12345-front.jpg"
        attachmentFilename: "LED-12345-front.jpg"
        attachmentLanguage: ["en-GB"]
        attachmentDescription:
          - language: "en-GB"
            attachmentDescription: "Front view product image"
  - attachmentRef: "att-datasheet-002"
    attachmentType: "ATX014"
    attachmentOrder: 2
    attachmentDetails:
      - attachmentUri: "https://cdn.manufacturer.com/products/datasheets/LED-12345-en.pdf"
        attachmentFilename: "LED-12345-datasheet-en.pdf"
        attachmentLanguage: ["en-GB"]
        attachmentIssueDate: "2024-06-15"
      - attachmentUri: "https://cdn.manufacturer.com/products/datasheets/LED-12345-de.pdf"
        attachmentFilename: "LED-12345-datasheet-de.pdf"
        attachmentLanguage: ["de-DE"]
        attachmentIssueDate: "2024-06-15"
